name: unit tests
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    env:
      CXX: g++-10
    steps:
      - name: get catch2
        run: 
          sudo apt update
          sudo apt install catch2
      - uses: actions/checkout@v2
      - name: build
        run: make
      - name: test
        run: ./test