name: unit tests
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: CXX=g++-10 make
      - name: test
        run: ./test